### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by bchaintreuil** [mroi/mount-diskimage#2]
Hey,

Can you compile and release directly the executable ? or explain to a newbie like me how to compile your project on Mac ?

Regards

**Comment by mroi** [comment]
Hi Benjamin,

> Can you compile and release directly the executable ?

I did not do that yet, because this whole technology lives quite deep inside the system and is not really meant to be fiddled with by users. My thinking was, that if I did provide binaries, I would present the illusion that it was all easy and supposedly stable.

That said, I could easily send you a link to my version of the binary, if that would help you. To install it, you have to get it into the /sbin directory, though. Since El Capitan, this directory is protected by SIP (system integrity protection, aka rootless) and can only be changed from the recovery partition using the command line. Do you think you feel comfortable with that?

After the scary setup is over, it seems to run pretty smoothly. I am using it since many versions of macOS/OS X now and it always seems to be compatible. Apple is probably not changing this part of the system much.

Regards,
Michael
